### ISSUE TITLE
"Unintentional" as a pathway 

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-fishes-checklist#3]
In the `description.csv` extension, I mapped the original pathways (e.g. `active migration` to the CBD standard (e.g. `cbd_2014_pathway:corridor_water`. However, for the original pathway `unintentional`, I couldn't find a good CBD alternative. This could be due to an escape, a contaminant, stowaway,... 
Any good suggestions, or do I contact Hugo Verreycken for the interpretation?

**Comment by damianooldoni** [comment]
I am working on improving pathway indicators and indeed, I see two fishes with a not standard CBD pathway:

- [141117236](https://www.gbif.org/species/141117236)
- [152543546](https://www.gbif.org/species/152543546)

Is there an update about this quite old issue?

**Comment by damianooldoni** [comment]
Still fighting against this issue while reading unified checklist data for indicators.

More insights:

1. for [141117236](https://www.gbif.org/species/141117236), I agree with @LienReyserhove: only `intentional` is used and it's not a standard pathway, but a macro category
2. for [152543546](https://www.gbif.org/species/152543546): as many unintentional pathways are present, `unintentional` can be removed without losing information

**Comment by damianooldoni** [comment]
Checked today with @LienReyserhove: this issue persists.

**Comment by LienReyserhove** [comment]
I checked this with the [pathway controlled vocabulary list of terms](https://dwc.tdwg.org/pw/) on the TDWG website, it appears that `unintentional` is a valid term after all, see [here](https://dwc.tdwg.org/pw/#dwcpw_p052). So I think this issue is resolved.
